name: VSSHKR
options:
  bundleIdPrefix: com.venafi
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "14.0"

targets:
  VSSHKR:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: VSSHKR
        excludes:
          - "**/*.md"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: VSSH-KR
        CFBundleIdentifier: com.venafi.vsshkr
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    # Dependencies will be managed by CocoaPods (see Podfile)
    # No SPM packages here to avoid conflicts
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.venafi.vsshkr
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      SWIFT_OBJC_BRIDGING_HEADER: ""
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"

